export const INTENT_EXECUTION_KEY_PREFIX = 'intent-execution:';
export const INTENT_EXECUTION_TTL_SECONDS = 2_592_000;
export const INTENT_EXECUTION_RETRY_AFTER_MS = 15 * 60 * 1000;
export const INTENT_EXECUTION_ANOMALY_RETRY_AFTER_MS = 6 * 60 * 60 * 1000;
export const INTENT_EXECUTION_TTL_WARNING_MS = 7 * 24 * 60 * 60 * 1000;
export const INTENT_EXECUTION_MAX_ATTEMPTS = 3;
