#!/bin/sh

cat > "$CI_PRIMARY_REPOSITORY_PATH/apps/ios/Secrets.xcconfig" << EOF
JSONRPC_API_KEY = $JSONRPC_API_KEY
ZERION_API_KEY = $ZERION_API_KEY

CLIENT_TOKEN = $CLIENT_TOKEN
RELAY_PROXY_HMAC_SECRET = $RELAY_PROXY_HMAC_SECRET
EOF
